server:
  port: 9001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.132:3306/tensquare_base?useUnicode=true&characterEncoding=utf8&useSSL=false
    password: 123
    username: root
  jpa:
    show-sql: true
    database: mysql
    generate-ddl: true
  application:
    name: tensquare-base
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true
